import { getChatGPTUser } from "../../../chatgpt-auth";
import { requiredSecret, runtime } from "../../../../lib/runtime";

const CATEGORIES = new Set(["Metronome", "Play-along", "Rhythm", "Ear training", "Technique", "Sight-reading", "Theory"]);

type ToolManifest = {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  version: 1;
  configuration: Record<string, unknown>;
};

async function github(path: string, token: string, init?: RequestInit) {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "practice-lab-publisher",
      ...(init?.headers ?? {}),
    },
  });
  const data = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw new Error(typeof data.message === "string" ? data.message : "GitHub request failed.");
  return data;
}

function validManifest(value: unknown): value is ToolManifest {
  if (!value || typeof value !== "object") return false;
  const tool = value as Partial<ToolManifest>;
  return (
    typeof tool.id === "string" &&
    /^[a-z0-9-]{3,64}$/.test(tool.slug ?? "") &&
    typeof tool.title === "string" &&
    tool.title.length <= 100 &&
    typeof tool.description === "string" &&
    tool.description.length <= 500 &&
    typeof tool.category === "string" &&
    CATEGORIES.has(tool.category) &&
    tool.version === 1 &&
    !!tool.configuration &&
    typeof tool.configuration === "object"
  );
}

export async function POST(request: Request) {
  const user = await getChatGPTUser();
  if (!user) return Response.json({ error: "Sign in is required." }, { status: 401 });
  const manifest = await request.json().catch(() => null);
  if (!validManifest(manifest)) return Response.json({ error: "The generated tool manifest is invalid." }, { status: 400 });

  let token: string;
  try {
    token = requiredSecret("GITHUB_TOKEN");
  } catch {
    return Response.json({ error: "GitHub publishing is not connected yet." }, { status: 503 });
  }

  const bindings = runtime();
  const repository = bindings.GITHUB_REPOSITORY ?? "bgoonz/MusicLab";
  const baseBranch = bindings.GITHUB_DEFAULT_BRANCH ?? "main";
  const [owner, repo] = repository.split("/");
  if (!owner || !repo) return Response.json({ error: "GitHub repository configuration is invalid." }, { status: 500 });

  try {
    const reference = await github(`/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(baseBranch)}`, token);
    const baseSha = (reference.object as { sha?: string } | undefined)?.sha;
    if (!baseSha) throw new Error("The default branch could not be resolved.");

    const branch = `practice-lab/tool-${manifest.slug}-${Date.now()}`;
    await github(`/repos/${owner}/${repo}/git/refs`, token, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    });

    const content = btoa(unescape(encodeURIComponent(`${JSON.stringify(manifest, null, 2)}\n`)));
    await github(`/repos/${owner}/${repo}/contents/generated-tools/${manifest.slug}.json`, token, {
      method: "PUT",
      body: JSON.stringify({
        message: `feat(tools): add ${manifest.title}`,
        content,
        branch,
      }),
    });

    const pullRequest = await github(`/repos/${owner}/${repo}/pulls`, token, {
      method: "POST",
      body: JSON.stringify({
        title: `Add practice tool: ${manifest.title}`,
        head: branch,
        base: baseBranch,
        body: `Generated by Practice Lab for review.\n\nCategory: ${manifest.category}\nSubmitted by: ${user.email}`,
        draft: true,
      }),
    });

    const pullRequestUrl = typeof pullRequest.html_url === "string" ? pullRequest.html_url : null;
    await bindings.DB.prepare(
      `INSERT INTO github_publications
       (id, tool_id, user_id, branch, pull_request_url, status, created_at)
       VALUES (?, ?, ?, ?, ?, 'review', ?)`,
    ).bind(crypto.randomUUID(), manifest.id, user.email.toLowerCase(), branch, pullRequestUrl, Date.now()).run();

    return Response.json({ pullRequestUrl, branch });
  } catch (error) {
    return Response.json({ error: error instanceof Error ? error.message : "Publishing failed." }, { status: 502 });
  }
}
