import { getChatGPTUser } from "../../../chatgpt-auth";
import { moderateText } from "../../../../lib/moderation";
import { requiredSecret, runtime } from "../../../../lib/runtime";
import { GeneratedToolSpec, isGeneratedToolSpec } from "../../../../lib/tool-spec";

async function github(path: string, token: string, init?: RequestInit) {
  const response = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "practice-lab-publisher",
      ...(init?.headers ?? {}),
    },
  });
  const data = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw new Error(typeof data.message === "string" ? data.message : "GitHub request failed.");
  return data;
}

function validManifest(value: unknown): value is GeneratedToolSpec {
  return isGeneratedToolSpec(value) && /^[a-z0-9-]{3,64}$/.test(value.slug);
}

export async function POST(request: Request) {
  const user = await getChatGPTUser();
  if (!user) return Response.json({ error: "Sign in is required." }, { status: 401 });
  const manifest = await request.json().catch(() => null);
  if (!validManifest(manifest)) return Response.json({ error: "The generated tool manifest is invalid." }, { status: 400 });

  let token: string;
  let apiKey: string;
  try {
    token = requiredSecret("GITHUB_TOKEN");
    apiKey = requiredSecret("AI_PROVIDER_API_KEY");
  } catch {
    return Response.json({ error: "Publishing safety services are not connected yet." }, { status: 503 });
  }

  try {
    const text = [
      manifest.title,
      manifest.description,
      JSON.stringify(manifest.configuration),
    ].join("\n");
    if (await moderateText(apiKey, text)) {
      return Response.json({ error: "This tool did not pass the publication safety review." }, { status: 400 });
    }
  } catch (error) {
    return Response.json(
      { error: error instanceof Error ? error.message : "The publication safety review could not be completed." },
      { status: 503 },
    );
  }

  const bindings = runtime();
  const repository = bindings.GITHUB_REPOSITORY ?? "bgoonz/MusicLab";
  const baseBranch = bindings.GITHUB_DEFAULT_BRANCH ?? "main";
  const [owner, repo] = repository.split("/");
  if (!owner || !repo) return Response.json({ error: "GitHub repository configuration is invalid." }, { status: 500 });

  try {
    const reference = await github(`/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(baseBranch)}`, token);
    const baseSha = (reference.object as { sha?: string } | undefined)?.sha;
    if (!baseSha) throw new Error("The default branch could not be resolved.");

    const branch = `practice-lab/tool-${manifest.slug}-${Date.now()}`;
    await github(`/repos/${owner}/${repo}/git/refs`, token, {
      method: "POST",
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
    });

    const content = btoa(unescape(encodeURIComponent(`${JSON.stringify(manifest, null, 2)}\n`)));
    const fileCommit = await github(`/repos/${owner}/${repo}/contents/generated-tools/${manifest.slug}.json`, token, {
      method: "PUT",
      body: JSON.stringify({
        message: `feat(tools): add ${manifest.title}`,
        content,
        branch,
      }),
    });

    const pullRequest = await github(`/repos/${owner}/${repo}/pulls`, token, {
      method: "POST",
      body: JSON.stringify({
        title: `Add practice tool: ${manifest.title}`,
        head: branch,
        base: baseBranch,
        body: `Generated by Practice Lab for review.\n\nCategory: ${manifest.category}\nSubmitted by: ${user.email}`,
        draft: true,
      }),
    });

    const pullRequestUrl = typeof pullRequest.html_url === "string" ? pullRequest.html_url : null;
    const repositoryCommit = (fileCommit.commit as { sha?: string } | undefined)?.sha ?? null;
    const authorName = user.fullName?.trim() || user.email.split("@")[0] || "Practice Lab musician";
    const now = Date.now();
    await bindings.DB.prepare(
      `INSERT INTO practice_tools
       (id, slug, title, description, category, source_path, manifest_json,
        repository_commit, author_id, author_name, status, use_count, created_at, published_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'published', 0, ?, ?)
       ON CONFLICT(id) DO UPDATE SET
         title = excluded.title,
         description = excluded.description,
         category = excluded.category,
         manifest_json = excluded.manifest_json,
         repository_commit = excluded.repository_commit,
         author_name = excluded.author_name,
         status = 'published',
         published_at = excluded.published_at
       WHERE practice_tools.author_id = excluded.author_id`,
    ).bind(
      manifest.id,
      manifest.slug,
      manifest.title,
      manifest.description,
      manifest.category,
      `generated-tools/${manifest.slug}.json`,
      JSON.stringify(manifest),
      repositoryCommit,
      user.email.toLowerCase(),
      authorName,
      now,
      now,
    ).run();
    await bindings.DB.prepare(
      `INSERT INTO github_publications
       (id, tool_id, user_id, branch, pull_request_url, status, created_at)
       VALUES (?, ?, ?, ?, ?, 'review', ?)`,
    ).bind(crypto.randomUUID(), manifest.id, user.email.toLowerCase(), branch, pullRequestUrl, now).run();

    return Response.json({ pullRequestUrl, branch });
  } catch (error) {
    return Response.json({ error: error instanceof Error ? error.message : "Publishing failed." }, { status: 502 });
  }
}
